Repository gip-inclusion/itou-communaute-django, pull requests merged in 2024-08, with the labels that each got.

#734 feat(forum): attr accept définit sur forms.ImageField
  config/settings/base.py
  lacommunaute/forum/forms.py
  lacommunaute/forum/tests/test_forum_updateview.py
Labels: python, just_an_idea

#737 fix(forum): balise `article` et dimension des images
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/templates/forum/forum_detail.html
  lacommunaute/templates/forum/forum_documentation.html
Labels: hot fix, templating

#712 feat(notification): passage des notifications en lues
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/forum_conversation/tests/tests_views_htmx.py
  lacommunaute/forum_conversation/views.py
  lacommunaute/forum_conversation/views_htmx.py
  lacommunaute/notification/admin.py
  lacommunaute/notification/factories.py
  lacommunaute/notification/models.py
  lacommunaute/notification/tests/tests_models.py
Labels: python

#742 fix(upvote): supprimer un parametrage ambigue
  lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/forum_conversation/views.py
  lacommunaute/templates/forum_conversation/topic_create_check.html
Labels: hot fix

#743 fix(upvotes): largeur du bouton s'abonner dynamique
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/templates/partials/upvotes.html
Labels: hot fix, python

#741 feat(documentation): rendre la certification optionnelle
  lacommunaute/forum/admin.py
  lacommunaute/forum/forms.py
  lacommunaute/forum/migrations/0016_forum_certified.py
  lacommunaute/forum/models.py
  lacommunaute/forum/tests/test_forum_updateview.py
  lacommunaute/forum/tests/tests_forms.py
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
  lacommunaute/search/__snapshots__/tests.ambr
  lacommunaute/templates/forum/forum_documentation.html
  lacommunaute/templates/forum/partials/forum_form.html
  lacommunaute/templates/partials/form_field.html
Labels: python, templating

#739 feat: mise à jour entête, pied de page et menu
  lacommunaute/forum_member/models.py
  lacommunaute/forum_member/tests/tests_models.py
  lacommunaute/forum_member/tests/tests_view.py
  lacommunaute/forum_member/urls.py
  lacommunaute/forum_member/views.py
  lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
  lacommunaute/pages/tests/test_homepage.py
  lacommunaute/static/vendor/theme-inclusion/images/home/bg-communaute-mobile.png
  lacommunaute/static/vendor/theme-inclusion/images/home/bg-communaute.png
  lacommunaute/static/vendor/theme-inclusion/images/home/illustration-01.png
  lacommunaute/static/vendor/theme-inclusion/images/home/illustration-02.png
  lacommunaute/static/vendor/theme-inclusion/images/home/search-bg-left.png
  lacommunaute/static/vendor/theme-inclusion/images/home/search-bg-right.png
  lacommunaute/static/vendor/theme-inclusion/images/logo-france-travail.svg
  lacommunaute/static/vendor/theme-inclusion/javascripts/app.js
  lacommunaute/static/vendor/theme-inclusion/stylesheets/app.css
  lacommunaute/templates/forum_conversation/partials/topic_filter.html
  lacommunaute/templates/pages/home.html
  lacommunaute/templates/partials/ask_a_question.html
  lacommunaute/templates/partials/footer.html
  lacommunaute/templates/partials/header.html
  lacommunaute/templates/partials/header_nav_primary_items.html
  lacommunaute/templates/partials/header_nav_secondary_items.html
Labels: python, templating

#748 fix(post): simplification du sujet des `Post`
  lacommunaute/forum_conversation/forms.py
  lacommunaute/forum_conversation/tests/tests_forms.py
Labels: python

#754 fix(forum_conversation): Résolution des erreurs de tests sur les contenus des messages
  lacommunaute/forum_conversation/tests/tests_forms.py
Labels: hot fix, python

#753 feat(event): amélioration de l'admin
  lacommunaute/event/admin.py
Labels: hot fix

#744 feat(tags): ajouter une étiquette inexistante à un sujet
  lacommunaute/forum_conversation/forms.py
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/templates/forum_conversation/partials/post_form.html
  lacommunaute/templates/forum_conversation/partials/topic_form.html
  lacommunaute/templates/forum_conversation/partials/topic_tags.html
  lacommunaute/templates/partials/form_field.html
Labels: python, templating

#746 feat(tags): ajouter des étiquettes à un forum
  lacommunaute/forum/admin.py
  lacommunaute/forum/factories.py
  lacommunaute/forum/forms.py
  lacommunaute/forum/migrations/0017_forum_tags.py
  lacommunaute/forum/models.py
  lacommunaute/forum/tests/__snapshots__/test_forum_updateview.ambr
  lacommunaute/forum/tests/test_forum_updateview.py
  lacommunaute/forum/tests/tests_forms.py
  lacommunaute/templates/forum/partials/forum_form.html
Labels: python

#750 feat(tags): filtrer les `forum` enfants à partir des tags
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum/views.py
Labels: python

#755 chore: mise à jour des dépendances
  poetry.lock
  requirements/base.txt
  requirements/dev.txt
Labels: dependencies
