Repository gip-inclusion/itou-communaute-django, pull requests merged in 2024-06, with the labels that each got.

#651 fix(quality): formatage des balises `script` dans le gabarit `base.html`
  lacommunaute/templates/forum_conversation/partials/post_feed.html
  lacommunaute/templates/layouts/base.html
  pyproject.toml
Labels: hot fix

#649 feat: ajout du chemin de fer dans l'espace d'échanges et la documentation
  lacommunaute/forum/factories.py
  lacommunaute/forum/models.py
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum/tests/tests_model.py
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum/views.py
  lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/search/__snapshots__/tests.ambr
  lacommunaute/static/stylesheets/itou_communaute.scss
  lacommunaute/surveys/tests/__snapshots__/test_views.ambr
  lacommunaute/templates/forum/forum_detail.html
  lacommunaute/templates/forum/forum_list.html
  lacommunaute/templates/forum_conversation/topic_detail.html
  lacommunaute/templates/layouts/base.html
  lacommunaute/templates/partials/breadcrumb.html
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
Labels: python

#656 feat(stats): ajout de la vue historique des visiteurs mensuels
  lacommunaute/forum_stats/tests/tests_views.py
  lacommunaute/forum_stats/urls.py
  lacommunaute/forum_stats/views.py
  lacommunaute/templates/forum_stats/monthly_visitors.html
  lacommunaute/templates/forum_stats/statistiques.html
Labels: python

#661 fix(stats): corrections mineures
  lacommunaute/forum_stats/tests/tests_views.py
  lacommunaute/forum_stats/urls.py
  lacommunaute/forum_stats/views.py
Labels: hot fix

#660 feat(stats): afficher les stats quotidiennes des Diagnostics Parcours IAE
  lacommunaute/forum_stats/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum_stats/tests/tests_views.py
  lacommunaute/forum_stats/urls.py
  lacommunaute/forum_stats/views.py
  lacommunaute/templates/forum_stats/base_detail_stats.html
  lacommunaute/templates/forum_stats/daily_dsp.html
  lacommunaute/templates/forum_stats/monthly_visitors.html
  lacommunaute/templates/forum_stats/statistiques.html
Labels: python

#666 feat(forum_conversation/admin): CertifiedPost verbose_name et traduction
  lacommunaute/forum_conversation/migrations/0007_certifiedpost.py
  lacommunaute/forum_conversation/models.py
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
Labels: python

#668 fix(forum_conversation): page 1 forcée dans les liens tags
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/templates/forum_conversation/partials/topic_tags.html
Labels: hot fix

#664 chore: supprimer l'accès aux django_auth_urls en mode productif
  config/urls.py
  lacommunaute/surveys/tests/test_views.py
  lacommunaute/utils/tests/__init__.py
  lacommunaute/utils/tests/tests_urls.py
  lacommunaute/utils/tests/tests_utils.py
Labels: hot fix

#672 fix(forum_moderation): motif de blocage illisible dans l'admin
  lacommunaute/forum_conversation/forms.py
  lacommunaute/forum_conversation/tests/tests_views_htmx.py
  lacommunaute/forum_moderation/enums.py
  lacommunaute/forum_moderation/models.py
  lacommunaute/forum_moderation/tests/test_post_disapprove_view.py
  lacommunaute/forum_moderation/views.py
Labels: hot fix, python

#684 fix(stats): derniere date collectée des stats matomo
  lacommunaute/forum_stats/management/commands/collect_matomo_stats.py
  lacommunaute/forum_stats/tests/tests_management_commands.py
Labels: hot fix

#687 fix(forum): ab test forum rating
  lacommunaute/templates/forum/forum_detail.html
Labels: hot fix

#688 fix(forum): ab test forum rating
  lacommunaute/forum/tests/__snapshots__/test_forum_rating_view.ambr
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/templates/forum/forum_detail.html
  lacommunaute/templates/forum/partials/rating.html
Labels: hot fix

#690 refactor(stats): renommage de l'app `forum_stats` en `stats`
  config/settings/base.py
  config/urls.py
  lacommunaute/forum/tests/test_categoryforum_listview.py
  lacommunaute/stats/__init__.py
  lacommunaute/stats/admin.py
  lacommunaute/stats/apps.py
  lacommunaute/stats/enums.py
  lacommunaute/stats/factories.py
  lacommunaute/stats/management/commands/collect_django_stats.py
  lacommunaute/stats/management/commands/collect_events.py
  lacommunaute/stats/management/commands/collect_matomo_stats.py
  lacommunaute/stats/management/commands/compute_answering_delay.py
  lacommunaute/stats/management/commands/export_counts.py
  lacommunaute/stats/migrations/0001_initial.py
  lacommunaute/stats/migrations/__init__.py
  lacommunaute/stats/models.py
  lacommunaute/stats/tests/__init__.py
  lacommunaute/stats/tests/__snapshots__/tests_views.ambr
  lacommunaute/stats/tests/tests_management_commands.py
  lacommunaute/stats/tests/tests_models.py
  lacommunaute/stats/tests/tests_views.py
  lacommunaute/stats/urls.py
  lacommunaute/stats/views.py
  lacommunaute/surveys/stats.py
  lacommunaute/surveys/tests/test_stats.py
  lacommunaute/templates/partials/footer.html
  lacommunaute/templates/stats/base_detail_stats.html
  lacommunaute/templates/stats/daily_dsp.html
  lacommunaute/templates/stats/monthly_visitors.html
  lacommunaute/templates/stats/statistiques.html
  lacommunaute/utils/matomo.py
Labels: python

#692 chore: suppression du tag manager matomo
  lacommunaute/templates/layouts/base.html
Labels: hot fix

#691 feat(stats): collecter les stats d'activité hebdo des forums de la documentation
  clevercloud/collect_weekly_matomo_forum_stats.sh
  clevercloud/cron.json
  lacommunaute/stats/admin.py
  lacommunaute/stats/factories.py
  lacommunaute/stats/management/commands/collect_matomo_forum_stats.py
  lacommunaute/stats/migrations/0002_forumstat.py
  lacommunaute/stats/models.py
  lacommunaute/stats/tests/tests_models.py
  lacommunaute/utils/date.py
  lacommunaute/utils/matomo.py
  lacommunaute/utils/tests/tests_utils.py
Labels: python
