Repository gip-inclusion/itou-communaute-django, pull requests merged in 2024-10, with the labels that each got.

#795 style: maj des classes utilitaires de font
  lacommunaute/forum/tests/__snapshots__/test_forum_rating_view.ambr
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
  lacommunaute/static/vendor/theme-inclusion/stylesheets/app.css
  lacommunaute/templates/forum/category_forum_list.html
  lacommunaute/templates/forum/partials/rating.html
  lacommunaute/templates/forum_conversation/forum_polls/poll_option_formset.html
  lacommunaute/templates/forum_conversation/partials/itou_modal.html
  lacommunaute/templates/forum_conversation/partials/topic_detail_actions.html
  lacommunaute/templates/forum_conversation/post_preview.html
  lacommunaute/templates/forum_conversation/topic_list.html
  lacommunaute/templates/pages/home.html
  lacommunaute/templates/partials/header.html
Labels: templating

#797 feat: suppression du sondage pour mieux connaitre les utilisateurs de la communauté
  lacommunaute/templates/layouts/base.html
Labels: hot fix

#794 fix: filtrage des questions en utilisant les étiquettes
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum_conversation/enums.py
  lacommunaute/forum_conversation/factories.py
  lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/forum_conversation/view_mixins.py
  lacommunaute/templates/forum_conversation/partials/topic_filter.html
  lacommunaute/templates/forum_conversation/partials/topic_tags.html
  lacommunaute/templates/forum_conversation/topic_list.html
  lacommunaute/templates/forum_conversation/topics_public.html
Labels: python, technical debt
