Repository gip-inclusion/itou-communaute-django, pull requests merged in 2024-09, with the labels that each got.

#757 feat(partner): ajout des pages partenaires
  config/settings/base.py
  config/urls.py
  lacommunaute/forum/management/commands/populate.py
  lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
  lacommunaute/partner/__init__.py
  lacommunaute/partner/admin.py
  lacommunaute/partner/apps.py
  lacommunaute/partner/factories.py
  lacommunaute/partner/migrations/0001_initial.py
  lacommunaute/partner/migrations/__init__.py
  lacommunaute/partner/models.py
  lacommunaute/partner/tests/__init__.py
  lacommunaute/partner/tests/__snapshots__/tests_partner_detailview.ambr
  lacommunaute/partner/tests/__snapshots__/tests_partner_listview.ambr
  lacommunaute/partner/tests/tests_model.py
  lacommunaute/partner/tests/tests_partner_detailview.py
  lacommunaute/partner/tests/tests_partner_listview.py
  lacommunaute/partner/urls.py
  lacommunaute/partner/views.py
  lacommunaute/templates/partials/breadcrumb_partner.html
  lacommunaute/templates/partials/footer.html
  lacommunaute/templates/partner/detail.html
  lacommunaute/templates/partner/list.html
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
Labels: python, templating

#761 feat(partner): lien avec les fiches pratiques
  lacommunaute/forum/admin.py
  lacommunaute/forum/factories.py
  lacommunaute/forum/forms.py
  lacommunaute/forum/management/commands/populate.py
  lacommunaute/forum/migrations/0018_forum_partner.py
  lacommunaute/forum/models.py
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum/tests/test_forum_updateview.py
  lacommunaute/forum/tests/tests_forms.py
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum/views.py
  lacommunaute/forum_conversation/views.py
  lacommunaute/partner/admin.py
  lacommunaute/partner/tests/__snapshots__/tests_partner_detailview.ambr
  lacommunaute/partner/tests/tests_partner_detailview.py
  lacommunaute/partner/views.py
  lacommunaute/templates/forum/forum_documentation.html
  lacommunaute/templates/forum/forum_documentation_category.html
  lacommunaute/templates/forum/partials/category_subforums_list.html
  lacommunaute/templates/forum/partials/forum_form.html
  lacommunaute/templates/forum/partials/partner.html
  lacommunaute/templates/partner/detail.html
  lacommunaute/utils/perms.py
  lacommunaute/utils/tests/tests_utils.py
Labels: python, templating

#763 feat(partner): améliorations post déploiement
  config/urls.py
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
  lacommunaute/partner/migrations/0002_alter_partner_options.py
  lacommunaute/partner/models.py
  lacommunaute/partner/tests/__snapshots__/tests_partner_detailview.ambr
  lacommunaute/partner/tests/__snapshots__/tests_partner_listview.ambr
  lacommunaute/partner/tests/tests_model.py
  lacommunaute/static/stylesheets/itou_communaute.scss
  lacommunaute/templates/partner/list.html
Labels: hot fix

#764 fix(partner): mise en forme des logos de la vue en liste
  lacommunaute/partner/tests/__snapshots__/tests_partner_listview.ambr
  lacommunaute/static/stylesheets/itou_communaute.scss
  lacommunaute/templates/partner/list.html
Labels: hot fix

#759 feat(partner): referencer les fiches partenaires dans sitemap.xml
  lacommunaute/pages/sitemaps.py
  lacommunaute/pages/tests/test_sitemap.py
  lacommunaute/pages/urls.py
Labels: python

#752 feat(tags): afficher les filtres sur les tags
  lacommunaute/forum/management/commands/populate.py
  lacommunaute/forum/tests/__snapshots__/test_subcategoryforum_listview.ambr
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum/tests/test_subcategoryforum_listview.py
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum/urls.py
  lacommunaute/forum/views.py
  lacommunaute/partner/tests/__snapshots__/tests_partner_detailview.ambr
  lacommunaute/templates/forum/forum_documentation_category.html
  lacommunaute/templates/forum/partials/category_subforums_list.html
  lacommunaute/templates/forum/partials/forum_tags.html
  lacommunaute/templates/forum/partials/subcategory_forum_list.html
  lacommunaute/templates/forum_conversation/partials/topic_tags.html
  lacommunaute/templates/partials/tag.html
  lacommunaute/templates/partner/detail.html
  lacommunaute/utils/testing.py
  lacommunaute/utils/tests/tests_utils.py
Labels: python, templating

#768 feat(forum): retrait des communautés privées
  lacommunaute/forum/admin.py
  lacommunaute/forum/enums.py
  lacommunaute/forum/factories.py
  lacommunaute/forum/migrations/0019_del_private_forum_20240905_1202.py
  lacommunaute/forum/migrations/0020_remove_forum_invitation_token_and_more.py
  lacommunaute/forum/models.py
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum/tests/test_categoryforum_listview.py
  lacommunaute/forum/tests/tests_model.py
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum_conversation/shortcuts.py
  lacommunaute/forum_conversation/tests/tests_shortcuts.py
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/forum_conversation/tests/tests_views_htmx.py
  lacommunaute/forum_member/tests/tests_view.py
  lacommunaute/forum_member/urls.py
  lacommunaute/forum_member/views.py
  lacommunaute/pages/tests/test_homepage.py
  lacommunaute/templates/forum/forum_detail.html
  lacommunaute/templates/forum/partials/topics_and_members_counts.html
  lacommunaute/templates/forum_member/moderator_profiles.html
Labels: python, templating, technical debt

#771 chore: mise à jour des dépendances
  poetry.lock
  requirements/base.txt
  requirements/dev.txt
Labels: dependencies

#772 fix: mise à jour des urls de statistiques
  lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
  lacommunaute/stats/tests/__snapshots__/tests_views.ambr
  lacommunaute/stats/urls.py
  lacommunaute/templates/partials/footer.html
  lacommunaute/templates/stats/forum_stat_week_archive.html
Labels: hot fix, technical debt

#774 feat(stats): ajout d'un lien vers la page de stats hebdos
  lacommunaute/stats/factories.py
  lacommunaute/stats/tests/__snapshots__/tests_views.ambr
  lacommunaute/stats/tests/tests_views.py
  lacommunaute/stats/urls.py
  lacommunaute/stats/views.py
  lacommunaute/templates/stats/forum_stat_week_archive.html
  lacommunaute/templates/stats/statistiques.html
Labels: python, templating

#769 feat(forum): retrait de la notion de `kind` sur `Forum`
  lacommunaute/forum/admin.py
  lacommunaute/forum/enums.py
  lacommunaute/forum/migrations/0021_remove_forum_kind.py
  lacommunaute/forum/models.py
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum/tests/test_categoryforum_createview.py
  lacommunaute/forum/tests/test_subcategoryforum_createview.py
  lacommunaute/forum/tests/tests_model.py
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum/views.py
  lacommunaute/forum_conversation/shortcuts.py
  lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum_conversation/tests/tests_shortcuts.py
  lacommunaute/forum_conversation/tests/tests_views.py
  lacommunaute/forum_conversation/urls.py
  lacommunaute/forum_conversation/views.py
  lacommunaute/forum_conversation/views_htmx.py
  lacommunaute/notification/tasks.py
  lacommunaute/notification/tests/tests_tasks.py
  lacommunaute/pages/sitemaps.py
  lacommunaute/pages/views.py
  lacommunaute/search/migrations/0002_remove_kind_in_materialized_view.py
  lacommunaute/search/tests.py
  lacommunaute/search/views.py
  lacommunaute/templates/404.html
  lacommunaute/templates/forum/forum_detail.html
  lacommunaute/templates/forum_conversation/topic_list_newsfeed.html
  lacommunaute/templates/forum_conversation/topics_newsfeed.html
  lacommunaute/templates/pages/home.html
  lacommunaute/templates/partials/breadcrumb.html
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
Labels: python, templating, technical debt

#776 feat: refonte homepage pour mise en valeur recherche et Call To Actions
  lacommunaute/forum/tests/__snapshots__/test_subcategoryforum_listview.ambr
  lacommunaute/forum/tests/__snapshots__/tests_views.ambr
  lacommunaute/forum_conversation/tests/__snapshots__/tests_views.ambr
  lacommunaute/pages/tests/__snapshots__/test_homepage.ambr
  lacommunaute/pages/tests/test_homepage.py
  lacommunaute/pages/views.py
  lacommunaute/static/images/APPRENDRE.png
  lacommunaute/static/images/DEMANDER.png
  lacommunaute/static/images/Microphone.png
  lacommunaute/static/images/SINFORMER.png
  lacommunaute/static/images/commu-home-illu-02b-light.png
  lacommunaute/static/images/home-banner-01-illu.png
  lacommunaute/static/images/home-illu-01.png
  lacommunaute/static/images/home-title-01-illu-card-01.png
  lacommunaute/static/images/home-title-01-illu-card-02.png
  lacommunaute/static/images/home-title-01-illu-card-03.png
  lacommunaute/static/images/hp-illustration-01.svg
  lacommunaute/static/images/logo-afpa.png
  lacommunaute/static/stylesheets/itou_communaute.scss
  lacommunaute/static/vendor/theme-inclusion/images/banner-01-illu.png
  lacommunaute/static/vendor/theme-inclusion/images/home-title-01-illu-card-01.png
  lacommunaute/static/vendor/theme-inclusion/images/home-title-01-illu-card-02.png
  lacommunaute/static/vendor/theme-inclusion/images/home-title-01-illu-card-03.png
  lacommunaute/static/vendor/theme-inclusion/images/home/commu-home-illu-01.png
  lacommunaute/static/vendor/theme-inclusion/images/home/commu-home-illu-02.png
  lacommunaute/static/vendor/theme-inclusion/images/logo-aides-territoires.svg
  lacommunaute/static/vendor/theme-inclusion/javascripts/app.js
  lacommunaute/static/vendor/theme-inclusion/stylesheets/app.css
  lacommunaute/templates/event/partials/event_date.html
  lacommunaute/templates/forum/partials/subcategory_forum_list.html
  lacommunaute/templates/forum_conversation/partials/itou_modal.html
  lacommunaute/templates/forum_conversation/topic_create_check.html
  lacommunaute/templates/pages/home.html
  lacommunaute/templates/partials/footer.html
  lacommunaute/templates/partials/header.html
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
Labels: python, templating

#777 chore(db): Améliorer l'hydratation de la base de données en developpement
  Makefile
  README.md
  scripts/import-latest-db-backup.sh
Labels: hot fix

#779 chore: mise à jour des dépendances
  poetry.lock
  requirements/base.txt
  requirements/dev.txt
Labels: dependencies

#781 feat: ajout d'un sondage pour mieux connaitre les utilisateurs de la communauté
  lacommunaute/templates/layouts/base.html
Labels: templating

#788 feat: page parking
  .env.template
  Makefile
  config/settings/base.py
  lacommunaute/templates/middleware/parking.html
  lacommunaute/utils/middleware.py
  lacommunaute/utils/tests/tests_middleware.py
Labels: python

#780 feat(partner): ajout des pages de creation / mise à jour depuis la page "nos partenaires"
  lacommunaute/forum/forms.py
  lacommunaute/forum/tests/tests_forms.py
  lacommunaute/partner/forms.py
  lacommunaute/partner/tests/__snapshots__/tests_partner_detailview.ambr
  lacommunaute/partner/tests/tests_forms.py
  lacommunaute/partner/tests/tests_partner_createview.py
  lacommunaute/partner/tests/tests_partner_listview.py
  lacommunaute/partner/tests/tests_partner_updateview.py
  lacommunaute/partner/urls.py
  lacommunaute/partner/views.py
  lacommunaute/templates/partner/create_or_update.html
  lacommunaute/templates/partner/detail.html
  lacommunaute/templates/partner/list.html
  lacommunaute/templates/partner/partials/partner_form.html
  lacommunaute/utils/html.py
  lacommunaute/utils/tests/tests_utils.py
Labels: python, templating
