Repository gip-inclusion/itou-communaute-django, pull requests merged in 2024-07, with the labels that each got.

#699 feat(admin): améliorer le filtrage des stats de forum
  lacommunaute/stats/admin.py
Labels: hot fix

#695 feat(stats): page hebdo partenaires fiches pratiques
  lacommunaute/forum/factories.py
  lacommunaute/forum/models.py
  lacommunaute/forum/tests/tests_model.py
  lacommunaute/stats/factories.py
  lacommunaute/stats/tests/__snapshots__/tests_views.ambr
  lacommunaute/stats/tests/tests_views.py
  lacommunaute/stats/urls.py
  lacommunaute/stats/views.py
  lacommunaute/templates/stats/forum_stat_week_archive.html
Labels: python

#701 feat(admin): filtrage des stats de forum, ajout tri
  lacommunaute/stats/admin.py
Labels: hot fix

#705 fix(cron.json): erreur copier-coller sur send_notifications_daily.sh
  clevercloud/cron.json
  clevercloud/send_notifications_daily.sh
  clevercloud/send_notifications_regular.sh
  lacommunaute/notification/management/commands/send_messages_notifications.py
Labels: hot fix

#708 feat(forum): fin de l'AB test sur la notation des forums
  lacommunaute/templates/forum/forum_detail.html
  lacommunaute/templates/forum/forum_documentation.html
Labels: templating

#710 chore: suppression des deprecation warning sur factory_boy
  lacommunaute/forum/factories.py
  lacommunaute/surveys/factories.py
  lacommunaute/users/factories.py
Labels: python

#719 chore: update dependencies
  poetry.lock
  requirements/base.txt
  requirements/dev.txt
Labels: dependencies

#720 feat(seo): mise à jour de l'image OpenGraph
  lacommunaute/static/images/logo-meta-communaute.png
  lacommunaute/static/images/logo-og-communaute.png
  lacommunaute/static/images/test.svg
  lacommunaute/templates/layouts/base.html
Labels: templating

#721 chore: bump to sentry-sdk from 1.45 to 2.11
  poetry.lock
  pyproject.toml
  requirements/base.txt
  requirements/dev.txt
Labels: dependencies

#723 chore: mise à jour de la version du script js sentry
  lacommunaute/templates/layouts/base.html
Labels: javascript

#725 feat(forum): utiliser l'image du forum dans la vignette opengraph
  lacommunaute/forum/forms.py
  lacommunaute/forum/tests/tests_views.py
  lacommunaute/forum/views.py
  lacommunaute/templates/layouts/base.html
Labels: python, templating

#730 feat(footer): mise à jour des liens sociaux
  lacommunaute/templates/partials/footer.html
Labels: templating

#732 fix: mise à jour de la public key sentry pour l'envoi des logs
  lacommunaute/templates/layouts/base.html
Labels: hot fix, javascript
